### ISSUE TITLE
Collab Summit 2024 Tasks

### ISSUE THREAD

**Issue by chrisgervang** [openjs-foundation/openvis-collab-space#4]
- [x] Is our [openvizsummit@openjs.org](mailto:openvizsummit@openjs.org) email still active? I'd like to refresh it with our current [TSC](https://github.com/visgl/tsc?tab=readme-ov-file#steering-committee-members).
- [x] Can we add a London 2024 tag added to this [repo](https://github.com/openjs-foundation/summit)
- [x] Please add london and collab summit tag to https://github.com/openjs-foundation/summit/issues/407 
- [x] Please update our OpenVis speaker's template with the 2024 tag and update any "new york" text to "london" https://github.com/openjs-foundation/summit/issues/new/choose
- [x] is it possible to make these slides open for comment to anyone with a link? https://docs.google.com/presentation/d/1b5R1UQEPW-jC1RpmQtuNS2wWeg7dkOAO_pIBDv-6B1U/edit

**Comment by bensternthal** [comment]
- Note the label 'London 2024 "was already used by Node so I created "OpenViz London 2024"
- PR for updating speakers template https://github.com/openjs-foundation/summit/pull/409
- Other tasks should be all set
